server:
  port: 80

spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:com/smart/coach/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl